services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8080:8000"
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: Social_Media_DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}

